---
- name: install dependencies
  apt: name={{ item }} state=present
  with_items: "{{ docker_dependencies }}"

- name: add gpg key
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D

- name: add deb repo
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main' state=present

- include: kernel_packages.yml
  when: docker_install_kernel_packages|bool and true

- name: install docker
  apt: name=docker-engine state=present
  notify:
    - start docker service

- name: add users to docker group
  user: name={{ item }} groups=docker append=yes
  with_items: "{{ docker_users }}"
